@startuml
interface Account{
    {abstract} +withdraw(): void
    {abstract} +getAccountNumber(): void
}

class ATM  {
    +withdraw(): void
    +getAccountNumber(): void
}

class BankAccount  {
    +withdraw(): void
    +getAccountNumber(): void
}

class Main  {
    {static} +main(String[]): void
}

Account <|.. ATM
Account <|.. BankAccount

interface Account  {
    {abstract} +withdraw(): void
    {abstract} +getAccountNumber(): void
}
@enduml